/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.moodanalyzer.controller;

public class MoodAnalyzerMain {
	// Constructor
	public MoodAnalyzerMain() {
	}

	public String analyseMood(String message) {
		if (message.contains("Sad"))
			return "SAD";
		else
			return "HAPPY";
	}
}
